'''<Summary>The DOM CompositionEvent represents events that occur due to the user indirectly entering text.</Summary>
<DynamicInterface(GetType(EcmaScriptObject))>
Public Interface [CompositionEvent]
'Defined on this type 
  '''<Summary>Returns the characters generated by the input method that raised the event; its varies depending on the type of event that generated the CompositionEvent object.</Summary>
  ReadOnly Property [data] As Dynamic
  '''<Summary>Creates a new CompositionEvent object instance.</Summary>
  Function [CompositionEvent]() As CompositionEvent
End Interface