'''<summary>The XPathResult interface represents the results generated by evaluating an XPath expression within the context of a given node.</summary>
<DynamicInterface(GetType(EcmaScriptObject))>
Public Interface [XPathResult]
  '''<summary>A boolean representing the value of the result if resultType is BOOLEAN_TYPE.</summary>
  ReadOnly Property [booleanValue] As String
  '''<summary>A number representing the value of the result if resultType is NUMBER_TYPE.</summary>
  ReadOnly Property [numberValue] As String
  '''<summary>A number code representing the type of the result, as defined by the type constants.</summary>
  ReadOnly Property [resultType] As Dynamic
  '''<summary>A Node representing the value of the single node result, which may be null.</summary>
  ReadOnly Property [singleNodeValue] As Node
  '''<summary>The number of nodes in the result snapshot.</summary>
  ReadOnly Property [snapshotLength] As Integer
  '''<summary>A string representing the value of the result if resultType is STRING_TYPE.</summary>
  ReadOnly Property [stringValue] As String
End Interface